name: Run Specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install sqlite3
      run: |
        sudo apt-get install libsqlite3-dev
    - name: Install elasticsearch
      run: |
        wget -O elasticsearch-7.6.0.tar.gz https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.6.0-linux-x86_64.tar.gz
        tar xvfz elasticsearch-7.6.0.tar.gz
        mkdir -p $HOME/elasticsearch/7.6.0
        mv elasticsearch-7.6.0 $HOME/elasticsearch/7.6.0
        cd $HOME/elasticsearch/7.6.0
        bin/elasticsearch -d
        for i in {1..12}; do wget -O- -v http://127.0.0.1:9200/ && break || sleep 5; done
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle install
        bundle exec appraisal install
        bundle exec appraisal rake spec
