name: Run Specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Java
      run: |
        sudo apt install -y openjdk-8-jdk
    - name: Install sqlite3
      run: |
        sudo apt-get install -y libsqlite3-dev
    - name: Setup ElasticSearch
      env:
        ELASTICSEARCH_PORT: 9200
        ELASTICSEARCH_VERSION: 6.8.7
      run: |
        curl -sSL https://raw.githubusercontent.com/codeship/scripts/master/packages/elasticsearch.sh | bash -s
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Check networks
      run: |
        lsof -i :9200
    - name: Build and test with Rake
      env:
        ELASTICSEARCH_URL: 'http://localhost:9200'
      run: |
        gem install bundler
        bundle install
        bundle exec rake spec
