name: Run Specs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Setup ElasticSearch
      uses: getong/elasticsearch-action@v1
      with:
        # Version of elasticsearch to use
        elasticsearch version: 7.6.1
    - name: Install sqlite3
      run: |
        sudo apt-get install -y libsqlite3-dev
    - name: Wait for Elasticsearch
      run: |
        for i in {1..12}; do wget -O- -v http://127.0.0.1:9200/ && break || sleep 5; done
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Check networks
      run: |
        lsof -i :9200
    - name: Build and test with Rake
      env:
        ELASTICSEARCH_URL: 'http://localhost:9200'
      run: |
        gem install bundler
        bundle install
        bundle exec rake spec
